spring:
  application:
    name: monew-batch
  profiles:
    active: prod
  config:
    import: optional:file:../.env[.properties],optional:file:.env[.properties]

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

batch:
  user-deletion:
    chunk-size: 10
    # [요구사항] 1일 후 삭제
    # [프로토타입] 5분으로 설정
    retention-minutes: 5

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    root: INFO

aws:
  accessKeyId: ${AWS_S3_ACCESS_KEY}
  secretKey: ${AWS_S3_SECRET_KEY}
  region: ${AWS_S3_REGION}
  bucket: ${AWS_S3_BUCKET}

naver:
    url: https://openapi.naver.com/v1/search/news.json
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}

rss:
  chosun:
    feeds:
      - https://www.chosun.com/arc/outboundfeeds/rss/?outputType=xml
      - https://www.chosun.com/arc/outboundfeeds/rss/category/politics/?outputType=xml
      - https://www.chosun.com/arc/outboundfeeds/rss/category/economy/?outputType=xml
      - https://www.chosun.com/arc/outboundfeeds/rss/category/national/?outputType=xml
      - https://www.chosun.com/arc/outboundfeeds/rss/category/international/?outputType=xml
      - https://www.chosun.com/arc/outboundfeeds/rss/category/culture-life/?outputType=xml
      - https://www.chosun.com/arc/outboundfeeds/rss/category/opinion/?outputType=xml
      - https://www.chosun.com/arc/outboundfeeds/rss/category/sports/?outputType=xml
      - https://www.chosun.com/arc/outboundfeeds/rss/category/entertainments/?outputType=xml

  hankyung:
    feeds:
      - https://www.hankyung.com/feed/economy
      - https://www.hankyung.com/feed/finance
      - https://www.hankyung.com/feed/realestate
      - https://www.hankyung.com/feed/it
      - https://www.hankyung.com/feed/politics
      - https://www.hankyung.com/feed/international
      - https://www.hankyung.com/feed/society
      - https://www.hankyung.com/feed/life
      - https://www.hankyung.com/feed/opinion
      - https://www.hankyung.com/feed/sports
      - https://www.hankyung.com/feed/entertainment

  yonhap:
    feeds:
      - https://www.yna.co.kr/rss/politics.xml
      - https://www.yna.co.kr/rss/economy.xml
      - https://www.yna.co.kr/rss/society.xml
      - https://www.yna.co.kr/rss/culture.xml
      - https://www.yna.co.kr/rss/sports.xml
      - https://www.yna.co.kr/rss/northkorea.xml
      - https://www.yna.co.kr/rss/international.xml
      - https://www.yna.co.kr/rss/local.xml

monew:
  api:
    url: http://localhost:8080