spring:
  application:
    name: monew-batch
  profiles:
    active: dev
  config:
    import: optional:file:../.env[.properties],optional:file:.env[.properties]

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

batch:
  user-deletion:
    chunk-size: 10
    # [요구사항] 1일 후 삭제
    # [프로토타입] 5분으로 설정
    retention-minutes: 5

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    root: INFO

aws:
  accessKeyId: ${AWS_S3_ACCESS_KEY}
  secretKey: ${AWS_S3_SECRET_KEY}
  region: ${AWS_S3_REGION}
  bucket: ${AWS_S3_BUCKET}

naver:
    url: https://openapi.naver.com/v1/search/news.json
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}

monew:
  api:
    url: http://localhost:8080