spring:
  application:
    name: monew-api
  profiles:
    active: prod
  config:
    import: optional:file:../.env[.properties],optional:file:.env[.properties]

aws:
  accessKeyId: ${AWS_S3_ACCESS_KEY}
  secretKey: ${AWS_S3_SECRET_KEY}
  region: ${AWS_S3_REGION}
  bucket: ${AWS_S3_BUCKET}